<?php

/**
 * @file
 * Contains ever.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ever_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ever module.
    case 'help.page.ever':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My first module that using Entity API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ever_theme() {
  return [
    'ever_entity_form' => [
      'render element' => 'form',
    ],
  ];
}
/**
 * Implements template_preprocess_HOOK().
 * Обработчик переменных для первого примера.
 */
function template_preprocess_ever(&$variables) {
  $date_formatter = \Drupal::service('date.formatter');
  $variables['date'] = $date_formatter->format(time());
}

